import express from "express";
import authApi from "./auth.router";
import lectureApi from "./lecture.router";
import cout from "../router/course.router";
import meeting from "../router/meeting.router";
import section from "../router/section";
import assignment from "../router/assignment";
import group from "../router/group.router";
import order from "../router/order";
const route = express.Router();
route.use("/auth", authApi);
route.use("/lesson", lectureApi);
route.use("/course", cout);
route.use("/meeting", meeting);
route.use("/section", section);
route.use("/assignment", assignment);
route.use("/group", group);
route.use("/order", order);
export default route;
