import express from "express";
import authApi from "./auth.router";
import lessionApi from "./lession.router";
import cout from "../router/course.router";
import meeting from "../router/meeting.router";
import section from "../router/section";
import assignment from "../router/assignment";
const route = express.Router();
route.use("/auth", authApi);
route.use("/lession", lessionApi);
route.use("/course", cout);
route.use("/meeting", meeting);
route.use("/section", section);
route.use("/assignment", assignment);
export default route;
